### ISSUE TITLE
up2date examples

### ISSUE THREAD

**Issue by vtolstov** [noxiouz/elliptics-go#32]
Hi! Can you update example , becasue i'm try it with latest elliptics and elliptics-go and need to fix it, because api of go package i changed.

**Comment by noxiouz** [comment]
Hi! I'll do

**Comment by noxiouz** [comment]
@vtolstov it's an updated example https://github.com/noxiouz/elliptics-go/blob/master/example/main.go

**Comment by vtolstov** [comment]
Thanks! I'm already have own example, but you code have more useful things =).
